theme: minima
title: Zweisprachiges Online-Wörterbuch der Phrasem-Konstruktionen
author: caracumba
email: kroelebor@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Zweisprachiges Online-Wörterbuch der Phrasem-Konstruktionen Deutsch-Russisch, Russisch-Deutsch

# social links
github_username:  caracumba

show_excerpts: true # set to false to remove excerpts on the homepage
